language: android

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository

jdk:
  - oraclejdk7
  - oraclejdk8

after_success:
  - ./gradlew coveralls

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
